/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BeginRouteImport } from './routes/begin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultTokenRouteImport } from './routes/result.$token'
import { Route as RTokenRouteImport } from './routes/r.$token'

const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginRoute = BeginRouteImport.update({
  id: '/begin',
  path: '/begin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTokenRoute = ResultTokenRouteImport.update({
  id: '/result/$token',
  path: '/result/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/begin': typeof BeginRoute
  '/cards': typeof CardsRoute
  '/privacy': typeof PrivacyRoute
  '/reflect': typeof ReflectRoute
  '/r/$token': typeof RTokenRoute
  '/result/$token': typeof ResultTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/begin': typeof BeginRoute
  '/cards': typeof CardsRoute
  '/privacy': typeof PrivacyRoute
  '/reflect': typeof ReflectRoute
  '/r/$token': typeof RTokenRoute
  '/result/$token': typeof ResultTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/begin': typeof BeginRoute
  '/cards': typeof CardsRoute
  '/privacy': typeof PrivacyRoute
  '/reflect': typeof ReflectRoute
  '/r/$token': typeof RTokenRoute
  '/result/$token': typeof ResultTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/begin'
    | '/cards'
    | '/privacy'
    | '/reflect'
    | '/r/$token'
    | '/result/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/begin'
    | '/cards'
    | '/privacy'
    | '/reflect'
    | '/r/$token'
    | '/result/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/begin'
    | '/cards'
    | '/privacy'
    | '/reflect'
    | '/r/$token'
    | '/result/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeginRoute: typeof BeginRoute
  CardsRoute: typeof CardsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReflectRoute: typeof ReflectRoute
  RTokenRoute: typeof RTokenRoute
  ResultTokenRoute: typeof ResultTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin': {
      id: '/begin'
      path: '/begin'
      fullPath: '/begin'
      preLoaderRoute: typeof BeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$token': {
      id: '/result/$token'
      path: '/result/$token'
      fullPath: '/result/$token'
      preLoaderRoute: typeof ResultTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeginRoute: BeginRoute,
  CardsRoute: CardsRoute,
  PrivacyRoute: PrivacyRoute,
  ReflectRoute: ReflectRoute,
  RTokenRoute: RTokenRoute,
  ResultTokenRoute: ResultTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
